#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := gbaHD

include $(IDF_PATH)/make/project.mk

#dependencies:
#	./get_components.sh
